
[phases.setup]
nixPkgs = ['unzip']
cmds = [
    'curl https://bun.sh/install | bash',
    'export BUN_INSTALL="$HOME/.bun"',
    'export PATH="$BUN_INSTALL/bin:$PATH"',
]

[phases.install    ]
cmds = ['bun install']

[start]
cmd = 'bun index.ts'
